# Generated by Django 5.0.7 on 2025-04-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('matches', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('postdate', models.DateField()),
                ('actions', models.CharField(max_length=100)),
            ],
        ),
    ]
