# Generated by Django 5.0.7 on 2025-04-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='phone',
        ),
        migrations.AddField(
            model_name='resume',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='parsed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='qualifications',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.JSONField(),
        ),
    ]
