# Generated by Django 5.0.7 on 2025-04-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_remove_resume_education_remove_resume_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
    ]
