# Generated by Django 5.0.7 on 2025-04-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_location_alter_resume_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
