# Generated by Django 5.0.7 on 2025-04-23 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_remove_job_actions_remove_job_matches'),
        ('resume', '0002_remove_resume_education_remove_resume_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Match percentage 0–100')),
                ('matched_skills', models.JSONField()),
                ('matched_experience', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='resume.resume')),
            ],
            options={
                'unique_together': {('job', 'resume')},
            },
        ),
    ]
