# Generated by Django 5.0.7 on 2025-04-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annalytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Reviewer notes'),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(default='Pending', help_text='Current candidate status', max_length=50),
        ),
    ]
